vi: vi
en: en
link_rails_tut: http://www.railstutorial.org/
help: http://www.railstutorial.org/help
book: http://www.railstutorial.org/book
ct: http://www.railstutorial.org/contact
ror: http://www.railstutorial.org/
ss: http://screencasts.railstutorial.org/
ruby: http://rybyonrails.org/
pcy: https://www.pinterest.com/phamtien2001/park-chanyeol-chibi/
news: http://news.railstutorial.org/
michaelhartl: http://www.michaelhartl.com/
